### ISSUE TITLE
Build a connector for the sim_platform project to read from the database artifact

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/db_utils#25]
- [ ] Put the code in db_utils, in a "Connector" folder, at the root of the repository.
- [ ] Link db_utils to sim_platform, so that the code editor can be used.
- [ ] On request of sim_platform, load a file from the database (code into the editor), the location of all issues of this file in the editor (markers in the left gutter: file name and line number, for all analysis tools).
- [ ] On request of sim_platform, load a warning's detailed information.

Keep the sim_platform requests programatic for the moment: in the main file. The others will take care of triggering them on a user event.

**Comment by rashmigupta1709** [comment]
1. Created a db connection with sqlite database from sim_platform
2. Parsing sarif files
3. Storing sarif files inside sqlite database
4. Created a pull request in sim_platform
