### ISSUE TITLE
Add translator script for analysis results from Checkmarx CSV to SARIF

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/db_utils#3]
- [x] Upload code [here](https://github.com/gapran/db_utils/tree/master/FormatTranslator).
- [x] Update documentation [here](https://github.com/gapran/db_utils/wiki#analysis-results-interpreters).
- [x] Upload the resulting SARIF files [here](https://github.com/gapran/db_utils/tree/master/scan_results/sarif).

* The raw files of Checkmarx should **not** be uploaded on to the repository.
* Make sure the SARIF files of Checkmarx are anonymized before uploading them on the repository.

**Comment by rashmigupta1709** [comment]
Hi Lisa, Could not upload the sarif files for checkmarx due to the security issue, could you remove this point from to-do list ?
